version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=info
      - REDIS_URL=${REDIS_URL}
      - WHATSAPP_TOKEN=${WHATSAPP_TOKEN}
      - WHATSAPP_VERIFY_TOKEN=${WHATSAPP_VERIFY_TOKEN}
      - WHATSAPP_PHONE_NUMBER_ID=${WHATSAPP_PHONE_NUMBER_ID}
      - WHATSAPP_INCOMING_PHONE_NUMBER=${WHATSAPP_INCOMING_PHONE_NUMBER}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_KEY=${ANTHROPIC_KEY}
      - AUTHORIZED_WHATSAPP_NUMBER=${AUTHORIZED_WHATSAPP_NUMBER}
      - MEDIA_STORAGE_PATH=/usr/src/app/tmp
    volumes:
      - ./src:/usr/src/app/src
      - ./nodemon.json:/usr/src/app/nodemon.json
      - ./tmp:/usr/src/app/tmp
    command: npm run dev
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:alpine
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge