name: CI/CD Pipeline for Dockerized Node.js App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set environment variables
      run: |
        echo "WHATSAPP_TOKEN=${{ secrets.WHATSAPP_TOKEN }}" >> $GITHUB_ENV
        echo "WHATSAPP_VERIFY_TOKEN=${{ secrets.WHATSAPP_VERIFY_TOKEN }}" >> $GITHUB_ENV
        echo "WHATSAPP_PHONE_NUMBER_ID=${{ secrets.WHATSAPP_PHONE_NUMBER_ID }}" >> $GITHUB_ENV
        echo "WHATSAPP_INCOMING_PHONE_NUMBER=${{ secrets.WHATSAPP_INCOMING_PHONE_NUMBER }}" >> $GITHUB_ENV
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
        echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> $GITHUB_ENV
        echo "ANTHROPIC_KEY=${{ secrets.ANTHROPIC_KEY }}" >> $GITHUB_ENV
        echo "AUTHORIZED_WHATSAPP_NUMBER=${{ secrets.AUTHORIZED_WHATSAPP_NUMBER }}" >> $GITHUB_ENV

    - name: Log in to DigitalOcean Registry
      run: echo "${{ secrets.DO_REGISTRY_TOKEN }}" | docker login -u "${{ secrets.DO_REGISTRY_USERNAME }}" --password-stdin registry.digitalocean.com

    - name: Build Docker image
      run: docker build -t registry.digitalocean.com/${{ secrets.DO_REPO_NAME }}/ray-ban-ai-assistant:${{ github.sha }} .

    - name: Push Docker image to DigitalOcean Registry
      run: docker push registry.digitalocean.com/${{ secrets.DO_REPO_NAME }}/ray-ban-ai-assistant:${{ github.sha }}

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy Docker container
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.REMOTE_PORT }} ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
          mkdir -p /var/www/ray-ban-ai-assistant
          chown -R $USER:$USER /var/www/ray-ban-ai-assistant
          cd /var/www/ray-ban-ai-assistant

          echo "Logging into Docker registry..."
          echo "${{ secrets.DO_REGISTRY_TOKEN }}" | docker login -u "${{ secrets.DO_REGISTRY_USERNAME }}" --password-stdin registry.digitalocean.com

          echo "Pulling Docker image..."
          docker-compose down
          docker-compose pull app
          docker-compose up -d --build
        EOF
      env:
        NODE_ENV: production
        TARGET: production
